export const DemoApi = {
  divisionGetActiveDetails: "/Services/DivisionService.asmx/GetActiveDetails",
  divisionGetActiveShort: "/Services/DivisionService.asmx/GetActiveShort",
  divisionGetDetailsById: "/Services/DivisionService.asmx/GetDetailsById",
  divisionAdd: "/Services/DivisionService.asmx/AddDivision",
  divisionUpdate: "/Services/DivisionService.asmx/UpdateDivision",
  divisionDelete: "/Services/DivisionService.asmx/DeleteDivision",
  divisionSelectedManagersList: "/Services/DivisionService.asmx/SelectedManagersList",
  divisionSetManagers: "/Services/DivisionService.asmx/SetManagers",
  divisionGetNotAssignedUsers: "/Services/DivisionService.asmx/GetNotAssignedUsersByBranchAndDivision",
  divisionAssignUsers: "/Services/DivisionService.asmx/AddUsersDivisionHistoryEntries",
  poolGetDetailsById: "/Services/ResourcePoolService.asmx/GetDetailsById",
  poolGetActiveShortByDivision: "/Services/ResourcePoolService.asmx/GetActiveShortByDivisionId",
  poolGetActiveShort: "/Services/ResourcePoolService.asmx/GetActiveShort",
  poolAdd: "/Services/ResourcePoolService.asmx/AddPool",
  poolUpdate: "/Services/ResourcePoolService.asmx/UpdatePool",
  poolDelete: "/Services/ResourcePoolService.asmx/DeletePool",
  poolGetNotAssignedUsers: "/Services/ResourcePoolService.asmx/GetNotAssignedUsersByPoolAndDivision",
  poolAssignUsers: "/Services/ResourcePoolService.asmx/AddUsersPoolHistoryEntries",
  poolUpdateUserDate: "/Services/ResourcePoolService.asmx/UpdateUserPoolHistoryDate",
  branchGetList: "/Services/BranchService.asmx/GetBranchGroupsWithBranchesList",
};
